name: teleop-utils
channels:
  - conda-forge
dependencies:
  - python=3.10
  - cxx-compiler
  - cmake
  - boost
  - spdlog
  - pybind11
  - zeromq
  - cppzmq
  - flask
  - flask-socketio
  - transforms3d
  - qrcode
  - pygame
  - pynput
  - click
  - av
  - opencv
  - pyzbar